name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          command_timeout: 120m
          script: |
            cd reactnd-project-would-you-rather
            git fetch
            git pull
            sudo docker-compose up -d --build
